# configuration/exceptions.py

class CredentialError(Exception):
    pass
